### ISSUE TITLE
Error on ZMQ socket bind() needs more information, patch attached.

### ISSUE THREAD

**Issue by jkempf42** [VOLTTRON/volttron-docker#63]
The current code in ./volttron/volttron/platform/vip/socket.py bind() prints out an error message saying that there was an attempt to bind an already bound socket. This is misleading, it could be due to any socket error. In particular, when building Volttron in a container, it may be due to the address not being assigned to the container. The attached git patch (renamed from *.patch to *.txt to be able to attach it) prints out the errno, and folks can simply go to their browser and look up the errno to find out what the problem is. 

         jak
[0001-Modified-socket.py-to-add-more-detail-on-the-error-m.txt](https://github.com/VOLTTRON/volttron-docker/files/8056843/0001-Modified-socket.py-to-add-more-detail-on-the-error-m.txt)
k

**Comment by bonicim** [comment]
Thanks, @jak42, for looking at this. I like how the patch provides more information to help the user when this error occurs. I have seen this error message before and have also found the error message unhelpful. Since this issue affects the actual Volttron codebase, I'll forward this issue to that repo, which is the better place for it. And thanks for the patch. I can get a quick PR out to get feedback from the community.

**Comment by bonicim** [comment]
Ok, since I don't have permissions to transfer this issue to https://github.com/VOLTTRON/volttron/issues, I'm just going create a new issue there and provide a link to this issue.

**Comment by bonicim** [comment]
Closing this issue as it will now be tracked in https://github.com/VOLTTRON/volttron/issues/2885
